### ISSUE TITLE
feat: Add a framework and minimalist template to kickstart project

### ISSUE THREAD

**Issue by maxime1992** [ghpabs/angular2-seed#20]
I think it might be a good idea to include Bootstrap or Foundation to this project.
People would probably be happy to have a basic menu with some routes as example to start a project very quickly.

**Comment by maxime1992** [comment]
And why not border line with angular material 2, bootstrap 4 or foundation 6 ?
Maybe it's too much work (for bootstrap4 and angular material 2) because they're only in alpha or not even available

**Comment by ghpabs** [comment]
I'd lean towards a modular framework (most of them already are) and lightweight when it comes to styling.

My preference at this point would be for [materializecss.com](http://materializecss.com/) as it supports Sass, looks neat and gives the user a bit of a break from the Bootstrapy look&feel.

**Comment by maxime1992** [comment]
I never used this framework and i love material design.
Would be a nice opportunity to learn !

**Comment by ghpabs** [comment]
It'd be nice to have this task thought-out in conjunction with #14.

**Comment by ghpabs** [comment]
After much talk I think we're running out of options for a framework that fits the bill. So let's have a go with  Bootstrap v4. I've created a new branch [feature/20](https://github.com/ghpabs/angular2-seed/tree/feature/20) so I can start playing with the implementation.
