### ISSUE TITLE
Deploy the project after running tests on Travis

### ISSUE THREAD

**Issue by maxime1992** [ghpabs/angular2-seed#22]
Would it be possible to auto deploy the project after running the tests ? 
I think it would be nice to have a demo of the app.

**Comment by ghpabs** [comment]
Options so far are Heroku and Nodejitsu.
Plus we'd need to create a hook in Travis to deploy the app after a successful build in `master`.

**Comment by maxime1992** [comment]
Seems pretty awesome to me !

**Comment by ghpabs** [comment]
Done in https://github.com/ghpabs/angular2-seed/commit/304703bec463bd3b2ca7403504dfcf995a6569a0.

View website at http://angular2-seed.io/ or source-code at https://github.com/ghpabs/angular2-seed/tree/gh-pages/.
