### ISSUE TITLE
doc: Create a wiki page for code standards

### ISSUE THREAD

**Issue by maxime1992** [ghpabs/angular2-seed#25]

**Comment by ghpabs** [comment]
How about we create a section in the `README.md` like **Resources** and list our best picks for code standard and other best practices?

**Comment by maxime1992** [comment]
@ghpabs Instead of the wiki ?

**Comment by ghpabs** [comment]
We could have Wiki pages. I'm wondering though if they'd be too high maintenance.

Any thoughts?

**Comment by maxime1992** [comment]
I think readme.md is for project description only, not to describe coding rules.

What about a contributing.md ? https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by ghpabs** [comment]
That's a cool feature! I think it'd be nice to have it. :+1:
