### ISSUE TITLE
Deploy app to a NodeJS web-server

### ISSUE THREAD

**Issue by ghpabs** [ghpabs/angular2-seed#30]
Unfortunately GitHub pages doesn't quite do the job here. It doesn't play nice with HTML5 routing, plus the relative paths are also screwed.

**HTML5 routing issue:**
1. Go to [angular2-seed.io](http://angular2-seed.io)
2. After page loading is completed refresh page.
3. 404. :-1: 

**Relative paths are screwed:**
1. Given the following website in GH Pages: https://USER.github.io/REPO/
2. In the HTML use the relative path notation eg.  `<script src="/foo/bar.js"></script>`
3. Expected path to resolve to `https://USER.github.io/REPO/foo/bar.js` but got `https://USER.github.io/foo/bar.js` instead. :-1: 

Need to start thinking again about Heroku or Nodejitsu.

**Comment by Hack-Point** [comment]
Yes I was unable to use this app in Heroku. Can you point out how to do that?

**Comment by ghpabs** [comment]
Hello. I haven't crossed this bridge yet so I'm afraid I can't help you much at the moment.

Having said that, the project only generates basic static components - HTML, CSS and JS - so you should be able to deploy it without much pain.

Have you tried checking Heroku's official documentation?

**Comment by maxime1992** [comment]
@ghpabs i don't understand why it doesn't play nice with html5. It's on client side so why github is involved here ?

**Comment by ghpabs** [comment]
@maxime1992 I've updated my original comment with a more detailed explanation about the issues.

**Comment by maxime1992** [comment]
@ghpabs instead of thinking to heroku for a frontend app, wouldn't it be simpler to have a dedicated gulp task ? Which replace `/foo/bar.js` by `https://USER.github.io/REPO/foo/bar.js` ?

**Comment by ghpabs** [comment]
Yes, that option came across my mind too. The problem is that we start changing the app to fit a specific ecosystem that won't be relevant to most people using this project. 

Ideally, we should be able to deploy the app as it ts. 

Any thoughts?

**Comment by maxime1992** [comment]
I don't know, it might make sense ! People might also want to deploy somewhere where they could have the same problem.
We could make a generic task which takes a base url and change all the path in index.html.

By default it would be empty, so it wouldn't change anything.

**Comment by ghpabs** [comment]
I've done a couple of changes - see https://github.com/ghpabs/angular2-seed/commit/ea1c5a6f9bdfd64452e009a15acdc43ac2da7c49 and https://github.com/ghpabs/angular2-seed/commit/04c8f042be6c7e3640bde154cd79f54694acca04.

Now we can deploy the app to Heroku which means we reduce the amount of code, there's no work-around for making things compatible with the server and the HTML5 routing works out-of-the-box.

Happy coding everyone! :christmas_tree: :santa:
