### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by NathanWalker** [ghpabs/angular2-seed#31]
This looks like a great seed setup, thanks for the efforts!

To avoid confusion in the community, could you please rename to something else?
Minko has had `angular2-seed` for quite a while before this. (https://github.com/mgechev/angular2-seed)

This is a great option though and renaming would help.

**Comment by gdi2290** [comment]
:+1:

**Comment by gdi2290** [comment]
tbh both repos are conflicting with angular's official seed https://github.com/angular/angular2-seed

**Comment by NathanWalker** [comment]
@gdi2290 oh wow! I didn't even know about that 3rd one. Looks like we should have a `name-off` ;)
First one to change the name wins. :+1:

**Comment by ghpabs** [comment]
Hi all,

I find that having the projects called `angular2-seed` is actually a good thing for consistency. In the end of the day you are left with only a couple of terms that can describe your project - angular2, ng2, boilerplate, seed... - and it becomes a matter of taste.

This name pattern `<framework>-seed` is more widespread than we might thing. I've done a quick search on GitHub's database and you can see them here:
- [react-seed](https://github.com/search?utf8=%E2%9C%93&q=%22react-seed%22)
- [backbone-seed](https://github.com/search?utf8=%E2%9C%93&q=%22backbone-seed%22)
- [angular-seed](https://github.com/search?utf8=%E2%9C%93&q=%22angular-seed%22&type=Repositories&ref=searchresults)
- [angular2-seed](https://github.com/search?utf8=%E2%9C%93&q=%22angular2-seed%22)

Also, devs can easily see the owner's name and the project description for distinction.

So to wrap it up, I won't be changing the repo's name - at least not for now.

I hope my view wasn't too disappointing. :-)

**Comment by NathanWalker** [comment]
@ghpabs I can appreciate your viewpoint. Reality is that having same name just creates practical problems not to mention user confusion when sifting through the array of information out there when coming to angular2.

Practical problem:
- Dev wants to contribute to this seed and another seed called `angular2-seed`
- They keep all angular2 repos in same folder on computer
- When they clone it, it creates name collisions where `git` auto renames dups to have suffix `-1`, `-2`, etc.
- Looking at the directory when trying to determine which is which is a face palm.

thanks.

**Comment by gdi2290** [comment]
ya I have angular2-seed, angular2-seed-1, and angular2-seed-2

**Comment by maxime1992** [comment]
If you really want to clone the repo, in the same directory as another angular2-seed, just `git clone https://github.com/ghpabs/angular2-seed.git angular2-seed-of-ghpabs`. Besides, it's a seed so it's a start for *your* project and you should just rename it as you wish `git clone https://github.com/ghpabs/angular2-seed.git my-super-angular2-project`.

**Comment by NathanWalker** [comment]
That makes sense for the savvy. Again, sadly though, it's not practical. 
A lot of devs have literally hundreds of repo's they are contributing to and may forget their `contributing` directory may already have a repo named as the same as yours, and alas, we are back to practicality and simplicity.

Your comment does not address:

> not to mention user confusion when sifting through the array of information out there when coming to angular2

**Comment by NathanWalker** [comment]
Your repo is very nice and should speak clearly to what it is.

The original here https://github.com/mgechev/angular2-seed is a true seed with no particular app setup in mind.

Yours is an implementation of a hero app.
`angular2-hero-app-seed` would not only help speak to the market about your repo, but also help newcomers to remember, oh yeah, that seed setup is closer to the type of app I'm trying to build because I remember that was the one like the hero app.

Just my 2 cents.

If your intent is to help the community with a solid seed. Naming is important and avoiding collisions with other repo's just helps that effort.

**Comment by ghpabs** [comment]
I could go on here, but I don't have the energy for such discussion.

**Comment by ghpabs** [comment]
Here we go guys, add your suggestions to this issue https://github.com/ghpabs/angular2-seed/issues/42.
