### ISSUE TITLE
Convert all the tests to TypeScript

### ISSUE THREAD

**Issue by Hack-Point** [ghpabs/angular2-seed#34]
You have tests that written in .js it's fairly uncomfortable I would like my whole eco-system to be in Typescript.

If you need I can convert it.

**Comment by ghpabs** [comment]
Feel free to put a PR through :-)

**Comment by ghpabs** [comment]
Done in https://github.com/ghpabs/angular2-seed/commit/9cac0491be8ebbf6a4a0cf9d2187b0c277e37c14 and https://github.com/ghpabs/angular2-seed/commit/23705b1d03d1c55238dc53f7af9158d5a1825dd2.
