### ISSUE TITLE
style: consistent indentation across all files

### ISSUE THREAD

**Issue by ghpabs** [ghpabs/angular2-seed#37]
Indentation should be 2 spaces across all files.

**Comment by ghpabs** [comment]
:lipstick:

**Comment by maxime1992** [comment]
Really ? Instead of tabs ?

**Comment by ghpabs** [comment]
Haha I like your reaction.

I find it a bit too much spacing when rendered in GitHub.
Take this file for example: https://github.com/ghpabs/angular2-seed/blob/master/gulpfile.js
Scroll to the bottom and look at the indentation. Isn't it a bit too much?

Even Angular2 team is using 2 spaces! :smile_cat: 
https://github.com/angular/angular/blob/master/.editorconfig

**Comment by maxime1992** [comment]
Arf you're right ... In github tabs are just too much.
But in sublime text or visual studio they're just perfect.

Damn i never noticed. Why did they do that to me :broken_heart: ... I cannot argue with angular repo as answer !

**Comment by maxime1992** [comment]
No for real, it's just a mater of taste and someone have to decide.
If you want to go with 2 spaces for indent let's change it !
(and prey for someone motivated enough to maintain a "tabs" fork :laughing: haha)

**Comment by ghpabs** [comment]
I'll think more about it. :+1:

**Comment by maxime1992** [comment]
I'm bothering you here but i gave a try in sublime. It's a bit tight but i guess it's just an habit to take ;) !

Anyway, it would be a good idea to wait a little bit and maybe have other opinions.
Also, it would be nice to decide a day/hour to change it (if you decide to) in order to avoid pull requests to fail (conflicts).

**Comment by ghpabs** [comment]
Sounds good, I'll post it here/Gitter before I change anything (if I do so).

**Comment by ghpabs** [comment]
Okay, so let's go with tabs. I've configured `.editorconfig` to display tab width of 2, plus `tslint` will raise a warning message if anyone tries to use spaces instead.
