### ISSUE TITLE
Add support for styleUrl and templateUrl

### ISSUE THREAD

**Issue by garywu125** [ghpabs/angular2-seed#40]

**Comment by ghpabs** [comment]
Do you get an error message in the console?

**Comment by garywu125** [comment]
I can not find component's html file in the destination folder , it seem
that we need a task to copy the component html somewhere !!!!!

**Comment by ghpabs** [comment]
Oh that's right, the HTML isn't being copied to the build folder.

Thanks for reporting it.

**Comment by ghpabs** [comment]
Any ideas about how this would work in production? 

Today all JS files (after being transpiled from TS) are concatenated and minified. Given that the folder structure is lost where would the template and style files be placed?
