### ISSUE TITLE
Make repo private

### ISSUE THREAD

**Issue by NathanWalker** [ghpabs/angular2-seed#41]
https://github.com/ghpabs/angular2-seed/issues/31

Making this private would solve 2 important things:
- Help others in the community that appreciate open conversation and understanding.
- Give author what they want. Their opinions.

**Comment by ghpabs** [comment]
Why is this so important to you Nathan?

**Comment by NathanWalker** [comment]
> I could go on here, but I don't have the energy for such discussion.

**Comment by ghpabs** [comment]
Please ask all others to change their name too.

**Comment by NathanWalker** [comment]
https://github.com/angular/angular2-seed/issues/26
